/**
 * Generate a measurement probe from contracts/unison.py.
 *
 *   node scripts/make-probe.mjs
 *
 * The probe reuses the contract's ACTUAL pure half -- the same anchors, the same
 * fact sheet, the same prompt builder, the same ballot parser -- by copying
 * everything above the "non-deterministic rounds" banner and appending three
 * methods that answer questions the real contract cannot:
 *
 *   sample   how far apart are two markings of the same source, from ONE node?
 *   plumbing does a nondet block whose validator always agrees settle at all?
 *   shape    does the leader's ballot survive calldata as the type the
 *            validator's shape check expects?
 *
 * Copying rather than importing is the point: a probe that re-derives the prompt
 * would measure the probe. This one measures the contract.
 *
 * A validator that always agrees is a rubber stamp and would be dishonest in a
 * product. It is correct in a ruler.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

const MARKER = "# The non-deterministic rounds.";

const source = readFileSync(join(ROOT, "contracts", "unison.py"), "utf8");
const cut = source.indexOf(MARKER);
if (cut < 0) throw new Error("unison.py no longer has the banner make-probe.mjs cuts at");

// Keep everything up to the banner, minus the trailing block comment lines.
let head = source.slice(0, cut);
head = head.slice(0, head.lastIndexOf("# ---"));

const probe = `

# ---------------------------------------------------------------------------
# Generated by scripts/make-probe.mjs. Not part of the product.
#
# Every round lives in a module level helper, exactly as the real contract does.
# The linter reads an inline run_nondet in a method that has already called a
# nondet helper as a NESTED block and refuses it, which is conservative but the
# structure it wants is the better one anyway.
# ---------------------------------------------------------------------------


def _always(_res: gl.vm.Result) -> bool:
    return True


def _fetch(url: str) -> str:
    def once() -> str:
        response = gl.nondet.web.get(url, headers={"Accept": "text/plain, */*"})
        body = response.body or b""
        if int(response.status) >= 400 or len(body) == 0:
            raise gl.vm.UserError(f"{ERROR_EXTERNAL} the source url answered {response.status}")
        return normalise(body.decode("utf-8", errors="replace"))

    return gl.eq_principle.strict_eq(once)


def _sample_round(url: str, source: str, count: int) -> dict:
    """Mark the same source several times on ONE node, and keep every vector.

    This is the ruler. If a single model marking a character-identical prompt
    cannot reproduce its own vector, no tolerance defined across nodes will
    settle either, and the fix is the rubric rather than the rule.
    """

    def once() -> dict:
        vectors = []
        for _ in range(count):
            reply = gl.nondet.exec_prompt(
                build_prompt("contract", url, source), response_format="json"
            )
            ballot = normalise_ballot("contract", reply, need_reasons=False)
            vectors.append([int(s) for s in ballot["scores"]])
        return {"vectors": vectors}

    return gl.vm.run_nondet(once, _always)


def _shape_round(url: str, source: str) -> dict:
    """Agree only if the leader's ballot survives calldata as the types
    ballot_is_sound expects. A systematic denial there would look exactly like a
    marking disagreement from outside, and would not be one."""

    def once() -> dict:
        reply = gl.nondet.exec_prompt(
            build_prompt("contract", url, source), response_format="json"
        )
        ballot = normalise_ballot("contract", reply)
        ballot["types"] = [type(s).__name__ for s in ballot["scores"]]
        return ballot

    def check(leaders_res: gl.vm.Result) -> bool:
        if not isinstance(leaders_res, gl.vm.Return):
            return False
        return ballot_is_sound("contract", leaders_res.calldata)

    return gl.vm.run_nondet(once, check)


class Probe(gl.Contract):
    log: DynArray[str]

    def __init__(self) -> None:
        pass

    @gl.public.view
    def read(self) -> str:
        if len(self.log) == 0:
            return ""
        return self.log[len(self.log) - 1]

    @gl.public.write
    def sample(self, url: str, times: int) -> None:
        source = _fetch(url)
        out = _sample_round(url, source, max(1, min(int(times), 5)))
        vectors = [[int(s) for s in v] for v in out["vectors"]]
        self.log.append(json.dumps({"vectors": vectors, "chars": len(source)}, sort_keys=True))

    @gl.public.write
    def shape(self, url: str) -> None:
        source = _fetch(url)
        out = _shape_round(url, source)
        scores = [int(s) for s in out["scores"]]
        types = [str(x) for x in (out.get("types") or [])]
        self.log.append(
            json.dumps({"shape": "agreed", "scores": scores, "types": types}, sort_keys=True)
        )
`;

const target = join(ROOT, "contracts", "_probe.py");
writeFileSync(target, head + probe, "utf8");
console.log(`wrote contracts/_probe.py (${(head + probe).length} bytes)`);
